// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=../mocks/auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeCreator is a mock of CodeCreator interface.
type MockCodeCreator struct {
	ctrl     *gomock.Controller
	recorder *MockCodeCreatorMockRecorder
	isgomock struct{}
}

// MockCodeCreatorMockRecorder is the mock recorder for MockCodeCreator.
type MockCodeCreatorMockRecorder struct {
	mock *MockCodeCreator
}

// NewMockCodeCreator creates a new mock instance.
func NewMockCodeCreator(ctrl *gomock.Controller) *MockCodeCreator {
	mock := &MockCodeCreator{ctrl: ctrl}
	mock.recorder = &MockCodeCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeCreator) EXPECT() *MockCodeCreatorMockRecorder {
	return m.recorder
}

// GenerateCode mocks base method.
func (m *MockCodeCreator) GenerateCode() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCode")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCode indicates an expected call of GenerateCode.
func (mr *MockCodeCreatorMockRecorder) GenerateCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCode", reflect.TypeOf((*MockCodeCreator)(nil).GenerateCode))
}
