// Code generated by MockGen. DO NOT EDIT.
// Source: ../session/session.go
//
// Generated by this command:
//
//	mockgen -source=../session/session.go -destination=../mocks/session.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	session "github.com/rancher/rancher/pkg/oidc/session"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockStorage) AddSession(code string, session session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", code, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSession indicates an expected call of AddSession.
func (mr *MockStorageMockRecorder) AddSession(code, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockStorage)(nil).AddSession), code, session)
}

// GetAndRemoveSession mocks base method.
func (m *MockStorage) GetAndRemoveSession(code string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndRemoveSession", code)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndRemoveSession indicates an expected call of GetAndRemoveSession.
func (mr *MockStorageMockRecorder) GetAndRemoveSession(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndRemoveSession", reflect.TypeOf((*MockStorage)(nil).GetAndRemoveSession), code)
}
