// Code generated by MockGen. DO NOT EDIT.
// Source: ./token.go
//
// Generated by this command:
//
//	mockgen -source=./token.go -destination=../mocks/token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSigningKeyGetter is a mock of SigningKeyGetter interface.
type MockSigningKeyGetter struct {
	ctrl     *gomock.Controller
	recorder *MockSigningKeyGetterMockRecorder
	isgomock struct{}
}

// MockSigningKeyGetterMockRecorder is the mock recorder for MockSigningKeyGetter.
type MockSigningKeyGetterMockRecorder struct {
	mock *MockSigningKeyGetter
}

// NewMockSigningKeyGetter creates a new mock instance.
func NewMockSigningKeyGetter(ctrl *gomock.Controller) *MockSigningKeyGetter {
	mock := &MockSigningKeyGetter{ctrl: ctrl}
	mock.recorder = &MockSigningKeyGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSigningKeyGetter) EXPECT() *MockSigningKeyGetterMockRecorder {
	return m.recorder
}

// GetPublicKey mocks base method.
func (m *MockSigningKeyGetter) getPublicKey(kid string) (*rsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getPublicKey", kid)
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockSigningKeyGetterMockRecorder) GetPublicKey(kid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getPublicKey", reflect.TypeOf((*MockSigningKeyGetter)(nil).getPublicKey), kid)
}

// GetSigningKey mocks base method.
func (m *MockSigningKeyGetter) GetSigningKey() (*rsa.PrivateKey, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getSigningKey")
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSigningKey indicates an expected call of GetSigningKey.
func (mr *MockSigningKeyGetterMockRecorder) GetSigningKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSigningKey", reflect.TypeOf((*MockSigningKeyGetter)(nil).GetSigningKey))
}
