// Code generated by MockGen. DO NOT EDIT.
// Source: ../token.go
//
// Generated by this command:
//
//	mockgen -source=../token.go -destination=./token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	session "github.com/rancher/rancher/pkg/oidc/session"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionGetter is a mock of sessionGetter interface.
type MocksessionGetter struct {
	ctrl     *gomock.Controller
	recorder *MocksessionGetterMockRecorder
	isgomock struct{}
}

// MocksessionGetterMockRecorder is the mock recorder for MocksessionGetter.
type MocksessionGetterMockRecorder struct {
	mock *MocksessionGetter
}

// NewMocksessionGetter creates a new mock instance.
func NewMocksessionGetter(ctrl *gomock.Controller) *MocksessionGetter {
	mock := &MocksessionGetter{ctrl: ctrl}
	mock.recorder = &MocksessionGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionGetter) EXPECT() *MocksessionGetterMockRecorder {
	return m.recorder
}

// GetAndRemove mocks base method.
func (m *MocksessionGetter) GetAndRemove(code string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndRemove", code)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndRemove indicates an expected call of GetAndRemove.
func (mr *MocksessionGetterMockRecorder) GetAndRemove(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndRemove", reflect.TypeOf((*MocksessionGetter)(nil).GetAndRemove), code)
}

// MocksigningKeyGetter is a mock of signingKeyGetter interface.
type MocksigningKeyGetter struct {
	ctrl     *gomock.Controller
	recorder *MocksigningKeyGetterMockRecorder
	isgomock struct{}
}

// MocksigningKeyGetterMockRecorder is the mock recorder for MocksigningKeyGetter.
type MocksigningKeyGetterMockRecorder struct {
	mock *MocksigningKeyGetter
}

// NewMocksigningKeyGetter creates a new mock instance.
func NewMocksigningKeyGetter(ctrl *gomock.Controller) *MocksigningKeyGetter {
	mock := &MocksigningKeyGetter{ctrl: ctrl}
	mock.recorder = &MocksigningKeyGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksigningKeyGetter) EXPECT() *MocksigningKeyGetterMockRecorder {
	return m.recorder
}

// GetPublicKey mocks base method.
func (m *MocksigningKeyGetter) GetPublicKey(kid string) (*rsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey", kid)
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MocksigningKeyGetterMockRecorder) GetPublicKey(kid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MocksigningKeyGetter)(nil).GetPublicKey), kid)
}

// GetSigningKey mocks base method.
func (m *MocksigningKeyGetter) GetSigningKey() (*rsa.PrivateKey, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSigningKey")
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSigningKey indicates an expected call of GetSigningKey.
func (mr *MocksigningKeyGetterMockRecorder) GetSigningKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSigningKey", reflect.TypeOf((*MocksigningKeyGetter)(nil).GetSigningKey))
}
